--- #YAML:1.0
name:                IPC-System-Simple
version:             0.06
abstract:            Call system() commands with a minimum of fuss
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Paul Fenwick <pjf@cpan.org>
